name: Build TrackWeight App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # 使用一个列表中可用的Xcode 16版本
          xcode-version: '16.2.0'

      # 第三步：编译应用，并跳过代码签名
      - name: Build and Archive an App (without signing)
        run: >
          xcodebuild -scheme TrackWeight archive
          -archivePath ./build/TrackWeight.xcarchive
          CODE_SIGN_IDENTITY=""
          CODE_SIGNING_REQUIRED=NO

      # 第四步：上传构件（不变）
      - name: Upload App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrackWeight-App
          path: ./build/TrackWeight.xcarchive/Products/Applications/TrackWeight.app

